Preping for Production release
ONSdigital/dp-frontend-release-calendar pull request #106
Opened 2022-09-01 12:33 UTC by yomiodeleye

### What
- 301 check spaces at end of translations
- 308 check full stop
- release.tmpl - also in other partials check alt text of kitemark, naming and captials
- comment for defaultWindowSize
- mapper.go line 348 consider returning default to avoid panic

### How to review

### Who can review
FD

2022-09-01 13:23 UTC, gilesburdett commented
Welsh locale has trailing spaces on lines:
- 301
- 313
- 317
- 321

2022-09-01 13:35 UTC, gilesburdett requested changes

2022-09-05 05:48 UTC, yomiodeleye commented on assets/templates/release.tmpl
> +          alt="UK Statistics Authority Kitemark"
I think the comment wast talking about capitalising 'Kitemark'

2022-09-05 05:51 UTC, yomiodeleye commented
regarding https://github.com/ONSdigital/dp-frontend-release-calendar/pull/106#issuecomment-1234277285
if we remove the spacing, the rendering in the frontend will be affected.  Because the template engine also factoring in the space from translations too.

2022-09-05 11:26 UTC, gilesburdett commented on mapper/mapper.go
> +/// defaultWindowSize is referring to pagination active link. Any links to the left or right of activeLink should not be grater than 5
Please replace this with:
```
// The current page number sits within a window, and the window size determines the 
// number of pages around the current page. For example a window size of 3 with the
// current page shown in () would give: 
// - (1) 2 3 at the start of the page range
// - 8 9 (10) at the end of the page range
// - 1 ... 5 (6) 7 ... 10 in the middle of the page range
```

2022-09-05 11:27 UTC, gilesburdett requested changes
Please change the comment to the text provided

2022-09-05 11:31 UTC, gilesburdett approved these changes

2022-09-06 09:00 UTC, merged